### ISSUE TITLE
Add signature to pass integrity check

### ISSUE THREAD

**Issue by grischdian** [tomneedham/loginprotect#1]
could you please sign your app so we can pass the integrity check ;)

see https://doc.owncloud.org/server/latest/developer_manual/app/advanced/code_signing.html?highlight=sign for more information

**Comment by tomneedham** [comment]
Sure - on it

**Comment by tomneedham** [comment]
Done! Released here: https://marketplace.owncloud.com/apps/loginprotect

**Comment by tomneedham** [comment]
And here https://github.com/tomneedham/loginprotect/releases/tag/v0.1.1
